import React from 'react';
import { Inter } from 'next/font/google';

import './globals.css';
import { ConfigProvider } from 'antd';
import StyledComponentsRegistry from '../lib/AntdRegistery';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <ConfigProvider theme={{
          token: {
            colorPrimary: '#0070f3',
          }
        }}
        >
          {children}
        </ConfigProvider>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;